"use client";

import ReactMarkdown from 'react-markdown'; // Optional: if you want formatted text later, but plain text works too

export default function ResultSection({ data }) {
  return (
    <div className="mt-10 max-w-3xl mx-auto p-6 bg-neutral-900 rounded-lg shadow-lg border border-neutral-800 animate-in fade-in slide-in-from-bottom-4 duration-700">
      
      <div className="flex justify-between items-center mb-4">
        <h2 className="text-2xl font-semibold text-green-400">Generated Result</h2>
        <span className="text-xs bg-neutral-800 px-2 py-1 rounded text-neutral-400">
           Generated by Gemini 2.5
        </span>
      </div>
      
      {/* The Main Content */}
      <div className="prose prose-invert max-w-none text-neutral-200 leading-relaxed whitespace-pre-wrap">
        {data.answer}
      </div>

    </div>
  );
}