"use client";

import ReactMarkdown from "react-markdown";
import { Copy, Check } from "lucide-react";
import { Prism as SyntaxHighlighter } from "react-syntax-highlighter";
import { oneDark } from "react-syntax-highlighter/dist/esm/styles/prism";
import { useState } from "react";

function CodeBlock({ inline, className, children }) {
  const [copied, setCopied] = useState(false);
  const match = /language-(\w+)/.exec(className || "");

  // INLINE CODE
  if (inline) {
    return (
      <code className="px-1.5 py-0.5 rounded bg-black/80 text-green-300 font-mono text-sm">
        {children}
      </code>
    );
  }

  const codeText = String(children).replace(/\n$/, "");

  const handleCopy = async () => {
    await navigator.clipboard.writeText(codeText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="relative my-6 rounded-lg overflow-hidden border border-neutral-800 bg-[#282c34]">
      {/* Code header */}
      <div className="flex justify-between items-center px-4 py-2 text-xs text-neutral-400 bg-neutral-900 border-b border-neutral-800">
        <span className="uppercase tracking-wide">
          {match?.[1] || "code"}
        </span>
        <button
          onClick={handleCopy}
          className="flex items-center gap-1.5 px-2 py-1 rounded border border-neutral-700 hover:border-green-600 hover:text-green-300 transition"
        >
          {copied ? <Check size={14} /> : <Copy size={14} />}
          {copied ? "Copied" : "Copy"}
        </button>
      </div>

      {/* Code body */}
      <SyntaxHighlighter
        language={match?.[1] || "text"}
        style={oneDark}
        customStyle={{
          margin: 0,
          background: "#282c34",
          fontSize: "0.85rem",
        }}
      >
        {codeText}
      </SyntaxHighlighter>
    </div>
  );
}

export default function ResultSection({ data }) {
  return (
    <div className="relative mt-12 max-w-3xl mx-auto rounded-xl overflow-hidden border border-neutral-800 bg-neutral-900 shadow-lg animate-in fade-in slide-in-from-bottom-6 duration-700">

      {/* Header */}
      <div className="flex items-center justify-between px-5 py-4 border-b border-neutral-800 bg-neutral-900/80 backdrop-blur">
        <h2 className="text-lg font-semibold tracking-wide text-green-400">
          ◆ Generated Output
        </h2>
      </div>

      {/* Content */}
      <div className="p-6 text-neutral-200 leading-relaxed">
        <ReactMarkdown
          components={{
            h1: props => <h1 className="text-2xl font-bold text-green-300 mt-6 mb-3" {...props} />,
            h2: props => <h2 className="text-xl font-semibold text-green-300 mt-5 mb-2" {...props} />,
            h3: props => <h3 className="text-lg font-semibold text-green-300 mt-4 mb-2" {...props} />,
            p: props => <p className="mb-4 leading-relaxed" {...props} />,
            ul: props => <ul className="list-disc ml-6 mb-4 space-y-1" {...props} />,
            ol: props => <ol className="list-decimal ml-6 mb-4 space-y-1" {...props} />,
            blockquote: props => (
              <blockquote className="border-l-4 border-green-600 pl-4 italic text-neutral-300 my-4" {...props} />
            ),
            code: CodeBlock,
          }}
        >
          {data.answer}
        </ReactMarkdown>
      </div>

      {/* Footer */}
      <div className="px-6 py-3 text-[11px] text-neutral-500 border-t border-neutral-800 bg-neutral-900/70">
        Generated by AI • Always review code before use
      </div>
    </div>
  );
}
